format = """
[╭─⎡$username$hostname⎦](green)
[│](green)$directory($git_status)($git_branch)($cmd_duration)($character)($battery)
[╰─▶](green) """

[cmd_duration]
format = " [$duration](bold yellow)"
min_time = 1_000

[git_status]
format='([ $all_status$ahead_behind]($style))'
modified="凜"
deleted="﫧"
staged=" "

[git_branch]
symbol = ""
format = " on [$symbol$branch]($style)"

[hostname]
ssh_only=false
format="[@](bold italic purple) [$hostname](bold italic blue) "

[username]
style_user="bold italic blue"
style_root="red bold"
format="[$user]($style) "
show_always=true

[directory]
format="[[$read_only](red)$path]($style)"
truncation_length=4
truncation_symbol="../"

[character]
format=" $symbol"
success_symbol=""
error_symbol="[❌Error!](red)"
vicmd_symbol="[](green)"

[battery]
charging_symbol=""
discharging_symbol=""
format = "[ $symbol$percentage](bold red)"
[[battery.display]]
threshold = 30
