#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources

[ -f $sysmodmap ] && xmodmap $sysmodmap

[ -f "$userresources" ] && xrdb -merge "$userresources"

[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Apply the custom key table
# [[ -f ~/.config/xmodmap ]] && xmodmap ~/.config/xmodmap



# Enable GPU
prime-offload &
# Compositor
picom --config "$XDG_CONFIG_HOME/picom/picom.conf" --log-file="/home/akim/tmp/picom-log.txt" &
# picom --log-level="DEBUG" --config="~/.config/picom/picom.conf" --inactive-opacity="0.6" --log-file="/home/akim/tmp/picom-log.txt" &
# Hotkey daemon
sxhkd &
# Set screen refresh rate
# xrandr -r 60

# Test config for the 2nd monitor
#xrandr --output DP-3 --scale 2
#xrandr --output DP-3 --mode 1920x1080 --rate 144

xrandr --output eDP-1 --primary --mode 3840x2400 --rate 60 --pos 0x720  --output DP-3 --mode 1920x1080 --rate 144 --pos 3840x0 --rotate left --scale 2

# Enable modules for DWM status bar
dwmblocks &
# Increase the rate at which pressed keys are processed
xset r rate 300 50
# Wallpaper
## Random wallpaper script located in ~/rps/bin
rwp
#xwallpaper --center $HOME/pix/wallpapers/alexandre_cabanel-fallen_angel.png &
# qutebrowser &
# alacritty -t "Performance" -e nvtop &
alacritty -t "Alacritty~" &

# The following prevents the screen going black after 10min (doesn't work)
# Disables Energy Star features
xset -dpms
# Disables screen saver
xset s off
# Start/restart WM w/o logging out
while type dwm 2>/dev/null; do dwm && continue || break; done
#while type dwm 2>$XDG_DATA_HOME/dwm/dwm.log; do dwm && continue || break; done

